name: Publish Docs on GitHub Page

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings[python]
      - name: Build site
        run: mkdocs build
      - name: List output files
        run: ls -la ./site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: libs/structpath
      - name: Deployment details
        run: |
          echo "Deployed to: https://$(echo ${{ github.repository_owner }}).github.io/$(echo ${{ github.event.repository.name }})/libs/structpath"
          echo "Published branch: gh-pages"
          echo "Published directory: ./site"
          echo "Destination directory: libs/structpath"
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"kl

